version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/research-with-programmers-api
    restart: always
    command: bash -c "npm install --omit=dev --legacy-peer-deps && npm run debug"
    volumes:
      - ./dist/:/usr/src/research-with-programmers-api/dist/
      - ./package.json:/usr/src/research-with-programmers-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
